CREATE TABLE IF NOT EXISTS messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  username text not null,
  content text not null,
  conversation_id text
);

CREATE TABLE IF NOT EXISTS message_likes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  message_id text not null,
  username text not null
);

CREATE TABLE IF NOT EXISTS follows (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  follower text not null,
  following text not null
);

CREATE TABLE IF NOT EXISTS notifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  username text not null,
  type text not null,
  from_user text not null,
  message text default '',
  reference_id text default '',
  read boolean default false
);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_all" ON messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "anon_all" ON message_likes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "anon_all" ON follows FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "anon_all" ON notifications FOR ALL USING (true) WITH CHECK (true);
